# Splunk Universal Forwarder - outputs.conf (Windows Server)
# Location: C:\Program Files\SplunkUniversalForwarder\etc\system\local\outputs.conf
# Replace <SPLUNK_IP> with your Splunk Enterprise Ubuntu VM IP address

[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = <SPLUNK_IP>:9997

[tcpout-server://<SPLUNK_IP>:9997]
